name: AI Review With Native Manual Approval

on: [workflow_dispatch]

jobs:
  comment-review:
    runs-on: ubuntu-latest
    outputs:
      review-report: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v3

      - name: Run AI Code Comment Review Agent
        uses: Manav-Khandurie/agents/code-comment-review-agent@code-comment-review-agent-v1.0.0
        with:
          config-path: "./QnABot/ai-comment-review.yaml"
          score-threshold: 85
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

      - name: Upload AI comment review result
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: code-comment-review-report
          path: code_comment_review_result.json

  manual-approval:
    runs-on: ubuntu-latest
    needs: comment-review
    environment:
      name: manual-approval  # 👈 Set this in GitHub repo settings with required reviewers
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Wait for manual approval
        run: echo "✅ Approved manually via environment reviewers"

      - name: Save human approval
        run: echo "yes" > human_approval.txt

      - name: Upload human decision
        uses: actions/upload-artifact@v4
        with:
          name: human-decision
          path: human_approval.txt

  determine-decision:
    runs-on: ubuntu-latest
    needs: [comment-review, manual-approval]
    outputs:
      proceed-to-print: ${{ steps.set-output.outputs.proceed }}
    steps:
      - name: Download AI review result
        uses: actions/download-artifact@v4
        with:
          name: code-comment-review-report

      - name: Try to download human approval
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: human-decision

      - name: Determine action
        id: set-output
        run: |
          if [[ -f human_approval.txt ]]; then
            echo "✅ Human approved"
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            COMMENT=$(jq -r '.code_comment' code_comment_review_result.json)
            echo "🤖 AI Decision: $COMMENT"
            if [[ "$COMMENT" == "true" ]]; then
              echo "proceed=true" >> $GITHUB_OUTPUT
            else
              echo "proceed=false" >> $GITHUB_OUTPUT
            fi
          fi

  print-job:
    runs-on: ubuntu-latest
    needs: determine-decision
    if: needs.determine-decision.outputs.proceed-to-print == 'true'
    steps:
      - run: echo "✅ Proceeding to PRINT job"

  ai-review:
    runs-on: ubuntu-latest
    needs: determine-decision
    if: needs.determine-decision.outputs.proceed-to-print == 'false'
    steps:
      - uses: actions/checkout@v3

      - name: Run AI Code Review Agent
        uses: Manav-Khandurie/agents/code-review-agent@code-review-agent-v1.1.0
        with:
          config-path: "./QnABot/ai-code-review.yaml"
          score-threshold: 75
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}

      - name: Upload AI review result
        uses: actions/upload-artifact@v4
        with:
          name: code-review-report
          path: code_review_result.json
